version: '3'


services:

  nsjail:
    build: ./nsjail


  ctfd_db:
    restart: always
    image: mariadb:10.4.7
    environment:
      - MYSQL_ROOT_PASSWORD=R9TS0oPt4HmPAIRvrwXUW4crbMCSCkxl
      - MYSQL_USER=kPuelPhzvwC1tVLIQFLsXMGFBTBLsNWO
      - MYSQL_PASSWORD=CarB3AH9mZqGJoDvuYui2GEgqmEYX0fV
      - MYSQL_DATABASE=ctfd
    volumes:
      - ./docker_volumes/ctfd/logs:/var/log
      - ./docker_volumes/ctfd/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - ctfd
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  ctfd_cache:
    restart: always
    image: redis:5.0.5
    user: root
    volumes:
      - ./docker_volumes/ctfd/logs:/var/log
      - ./docker_volumes/ctfd/redis:/data
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - ctfd

  ctfd:
    restart: always
    build: ./CTFd
    depends_on:
      - ctfd_db
      - ctfd_cache
    user: root
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=mysql+pymysql://kPuelPhzvwC1tVLIQFLsXMGFBTBLsNWO:CarB3AH9mZqGJoDvuYui2GEgqmEYX0fV@ctfd_db:3306/ctfd
      - REDIS_URL=redis://ctfd_cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - UPLOAD_FOLDER=/var/uploads
      - ACCESS_LOG=/var/log/CTFd/access_log
      - ERROR_LOG=-
      - USE_RELOAD=false
    volumes:
      - ./docker_volumes/ctfd/logs:/var/log
      - ./docker_volumes/ctfd/uploads:/var/uploads
      - ./CTFd:/opt/CTFd:ro
    expose:
      - 8000
    ports:
      - "127.0.0.1:1337:8000"
    networks:
      - default
      - ctfd


  tasks:
    restart: "no"
    image: tianon/true
    depends_on:
      - cookie_sqli

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cookie_sqli
      POSTGRES_PASSWORD: pDYAPV84eg2c9moNDSLWAeVelHKlUN
      POSTGRES_APP_USER: cookie_sqli
      POSTGRES_APP_PASSWORD: h6LEupySib86eMna5w9BuRzD0sm2vI
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  cookie_sqli:
    restart: always
    build: ./tasks/cookie_sqli
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    expose:
      - 8000
    ports:
      - "127.0.0.1:1338:8000"

networks:
  ctfd:
    internal: true
