version: '3'


services:


  ctfd:
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=mysql+pymysql://kPuelPhzvwC1tVLIQFLsXMGFBTBLsNWO:CarB3AH9mZqGJoDvuYui2GEgqmEYX0fV@ctfd_db:3306/ctfd
      - REDIS_URL=redis://ctfd_cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - UPLOAD_FOLDER=/var/uploads
      - ACCESS_LOG=/var/log/CTFd/access_log
      - ERROR_LOG=-
      - USE_RELOAD=false
      - USE_SSL=false
      - REVERSE_PROXY=true
    ports:
      - "8000:8000"
    networks:
      - ctfd

  nginx:
    restart: always
    image: nginx:1.17.3
    depends_on:
      - ctfd
    hostname: ctf.staszic.waw.pl
    volumes:
      - ./ssl:/etc/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker_volumes/nginx/logs:/var/log/nginx
    expose:
      - 8000
      - 8443
    ports:
      - "10.0.13.37:80:8000"
      - "10.0.13.37:443:8443"
    networks:
      - default
      - ctfd
